const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id: '2',
            name: 'Adidas Slim Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 100,
            brand: 'Adidas',
            rating: 4.7,
            numReviews: 14,
            description: 'High quality genuine product',
        },
        {
            _id: '3',
            name: 'Puma Slim Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 125,
            brand: 'Puma',
            rating: 4.3,
            numReviews: 30,
            description: 'High quality awesome product',
        },
        {
            _id: '4',
            name: 'Nike Slim Pant',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 130,
            brand: 'Nike',
            rating: 4.6,
            numReviews: 17,
            description: 'High quality pant',
        },
        {
            _id: '5',
            name: 'Adidas Slim Pant',
            category: 'Pants',
            image: '/images/p5.jpg',
            price: 160,
            brand: 'Adidas',
            rating: 4.9,
            numReviews: 100,
            description: 'High quality amusing product',
        },
        {
            _id: '6',
            name: 'Puma Slim Pant',
            category: 'Pants',
            image: '/images/p6.jpg',
            price: 90,
            brand: 'Puma',
            rating: 4.4,
            numReviews: 51,
            description: 'High quality product with guarantee',
        },
    ],
};
export default data;